
image: registry.gitlab.com/csicar/purescript-sized-matrices

cache:
   key: "$CI_COMMIT_REF_SLUG"
   paths:
      - .bower_cache

build:
   stage: build
   script:
      - mkdir -p .bower_cache
      - mkdir -p ~/.cache/bower
      - cp -r .bower_cache ~/.cache/bower
      - bower install
      - cp -r ~/.cache/bower .bower_cache
      - pulp test