
image: registry.gitlab.com/csicar/purescript-sized-matrices

cache:
   key: "$CI_COMMIT_REF_SLUG"
   paths:
      - .bower_cache

# Moves the bower-cache files into .bower_cache, since
# gitlab-ci can only cache files in the project directory
before_script:
   - mkdir -p .bower_cache
   - mkdir -p ~/.cache/bower
   - cp -a .bower_cache/. ~/.cache/bower

build:
   stage: build
   script:
      - bower install -q
      - pulp build
   artifacts:
      paths:
         - output
         - bower_components

test:
   stage: test
   script:
      - pulp test

after_script:
   - cp -a ~/.cache/bower/. .bower_cache