
image: registry.gitlab.com/csicar/purescript-sized-matrices

cache:
   key: "$CI_COMMIT_REF_SLUG"
   paths:
      - .bower_cache

before_script:
   - mkdir -p .bower_cache
   - mkdir -p ~/.cache/bower
   - ls .bower_cache
   - cp -a .bower_cache/. ~/.cache/bower
   - ls ~/.cache/bower

build:
   stage: build
   script:
      - bower install -q
      - pulp test

after_script:
   - cp -a ~/.cache/bower/. .bower_cache
   - ls ~/.cache/bower
   - ls .bower_cache